name: "cas asset"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    env:
      CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
      CAS_SIGNER_ID: ${{ secrets.CAS_SIGNER_ID }}
    steps:
      - name: cas notarize asset
        uses: codenotary/cas-notarize-asset-github-action@1.0.0
      - name: cas authorize asset
        uses: codenotary/cas-authenticate-asset-github-action@1.0.0  
